# Generated by Django 3.2.15 on 2022-09-17 09:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OOIInformation',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(null=True)),
                ('consult_api', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126, unique=True)),
                ('code', models.CharField(default=None, max_length=8, null=True, unique=True)),
                ('signal_username', models.CharField(blank=True, max_length=126, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+99999999999'. 11 digits allowed.", regex='^\\+?1?\\d{11,11}$')])),
                ('signal_group_id', models.CharField(blank=True, max_length=126, null=True)),
            ],
            options={
                'permissions': (('can_switch_organization', 'Can switch organization'), ('can_scan_organization', 'Can scan organization'), ('can_enable_disable_boefje', 'Can enable or disable boefje')),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('authorized', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('new', 'new'), ('blocked', 'blocked')], default='new', max_length=64)),
                ('member_name', models.CharField(max_length=126)),
                ('member_role', models.CharField(max_length=126)),
                ('goal', models.CharField(max_length=256)),
                ('signal_username', models.CharField(blank=True, default=None, max_length=126, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+99999999999'. 11 digits allowed.", regex='^\\+?1?\\d{11,11}$')])),
                ('onboarded', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tools.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boefje_id', models.CharField(max_length=128)),
                ('input_ooi', models.TextField(null=True)),
                ('arguments', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Indemnification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
